// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace SellerManager.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20211210125714_InitialModel")]
    partial class InitialModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("Seller", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DiscountFactor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Sellers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7aec76ad-e684-4a24-8418-35c41faccc39"),
                            Address = "947 Heritage Road",
                            CreatedAt = new DateTime(2021, 12, 10, 12, 57, 14, 488, DateTimeKind.Utc).AddTicks(1735),
                            DiscountFactor = 10m,
                            Email = "John@mail.com",
                            Name = "John Smith"
                        },
                        new
                        {
                            Id = new Guid("b71d5e76-ff10-4bcc-b772-d248ce953093"),
                            Address = "360 Bates Brothers Road",
                            CreatedAt = new DateTime(2021, 12, 10, 12, 57, 14, 488, DateTimeKind.Utc).AddTicks(1739),
                            DiscountFactor = 10m,
                            Email = "vmarshall@mail.com",
                            Name = "Violet Marshall"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
